"""Global configuration constants for training ML model."""

MODEL_NAME = "distilbert-base-uncased"
DECISION_THRESHOLD = 0.5

MOOD_TAGS = [
    "007",
    "007 (series)",
    "18th century",
    "1920s",
    "1930s",
    "1950s",
    "1960s",
    "1970s",
    "1980s",
    "19th century",
    "3d",
    "70mm",
    "80s",
    "9/11",
    "aardman",
    "aardman studios",
    "abortion",
    "absurd",
    "action",
    "action packed",
    "adaptation",
    "adapted from:book",
    "adapted from:comic",
    "adapted from:game",
    "addiction",
    "adolescence",
    "adoption",
    "adultery",
    "adventure",
    "affectionate",
    "afi 100",
    "afi 100 (laughs)",
    "afi 100 (movie quotes)",
    "africa",
    "afterlife",
    "aging",
    "aids",
    "airplane",
    "airport",
    "alaska",
    "alcatraz",
    "alcoholism",
    "alien",
    "alien invasion",
    "aliens",
    "allegory",
    "almodovar",
    "alone in the world",
    "alter ego",
    "alternate endings",
]
